/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dominio.Producto;
import dominio.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicio.ProductoServicio;
import java.sql.SQLException;

/**
 *
 * @author jh599
 */

public class gui_gestion_productos extends javax.swing.JFrame {

    /**
     * Creates new form gui_gestion_productos
     */
    
    
    private Usuario usuarioLogueado;
    private ProductoServicio productoService;
private Producto productoSeleccionado; 
private boolean editando = false;

    public gui_gestion_productos(Usuario usuario) {
      this.usuarioLogueado = usuario;
    this.productoService = new ProductoServicio();
    this.productoSeleccionado = null;
    
    initComponents();
    
    // Configurar botón refrescar 
    btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefrescarActionPerformed(evt);
        }
    });
    
    cargarProductosEnTabla();
    setLocationRelativeTo(null);
    }
    
    
private void cargarProductosEnTabla() {
    try {
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();
        modelo.setRowCount(0); // ✅ Limpia todas las filas antes de cargar

        List<Producto> productos = productoService.listarProductos();
        for (Producto p : productos) {
            Object[] fila = {
                p.getId(),
                p.getNombre(),
                String.format("%.2f", p.getPrecioUnitario()),
                p.isActivo() ? "Activo" : "Inactivo"
            };
            modelo.addRow(fila);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "❌ Error al cargar productos.");
        e.printStackTrace();
    }
}

private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {
    int fila = tblProductos.getSelectedRow();
    if (fila >= 0) {
        int id = (int) tblProductos.getValueAt(fila, 0);
        try {
            productoSeleccionado = productoService.obtenerProductoPorId(id);
            if (productoSeleccionado != null) {
                txtNombreProducto.setText(productoSeleccionado.getNombre());
                jFormattedTextField1.setText(String.valueOf(productoSeleccionado.getPrecioUnitario()));
                jCheckBox.setSelected(productoSeleccionado.isActivo());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar producto.");
            e.printStackTrace();
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCrud = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnActivarDesactivar = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jCheckBox = new javax.swing.JCheckBox();
        lblNombreProducto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnActivarDesactivar.setText("Activar/Desactivar");
        btnActivarDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarDesactivarActionPerformed(evt);
            }
        });

        jCheckBox.setText("Activo/Inactivo");

        lblNombreProducto.setText("Nombre del producto: ");

        lblPrecio.setText("Precio: ");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrudLayout = new javax.swing.GroupLayout(panelCrud);
        panelCrud.setLayout(panelCrudLayout);
        panelCrudLayout.setHorizontalGroup(
            panelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrudLayout.createSequentialGroup()
                .addGroup(panelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrudLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)
                        .addGap(18, 18, 18)
                        .addComponent(btnActivarDesactivar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefrescar))
                    .addGroup(panelCrudLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblNombreProducto)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox))
                    .addGroup(panelCrudLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        panelCrudLayout.setVerticalGroup(
            panelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrudLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox)
                    .addGroup(panelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreProducto)
                        .addComponent(lblPrecio)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnNuevo)
                    .addComponent(btnVolver)
                    .addComponent(btnActivarDesactivar)
                    .addComponent(btnRefrescar))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCrud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 try {
        String nombre = txtNombreProducto.getText().trim();
        String precioStr = jFormattedTextField1.getText().trim();

        // Validaciones mínimas en GUI 
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ El nombre es obligatorio.");
            return;
        }
        if (precioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Ingresa un precio.");
            return;
        }

        double precio;
        try {
            precio = Double.parseDouble(precioStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "⚠️ Precio inválido.");
            return;
        }

        boolean activo = jCheckBox.isSelected();

        // ✅ Llamada al servicio (aquí va toda la lógica)
        productoService.guardarProducto(nombre, precio, activo, productoSeleccionado);

        // ✅ Éxito: actualizar vista
        cargarProductosEnTabla();
        limpiarFormulario();
        JOptionPane.showMessageDialog(this, "✅ Producto guardado con éxito.");

    } catch (IllegalArgumentException e) {
        // Error de validación
        JOptionPane.showMessageDialog(this, "⚠️ " + e.getMessage());
    } catch (SQLException e) {
        // Error de base de datos
        JOptionPane.showMessageDialog(this, "❌ Error al guardar en la base de datos.");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       limpiarFormulario();
    editando = false;
    productoSeleccionado = null;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      int fila = tblProductos.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "⚠️ Selecciona un producto para editar.");
        return;
    }
    editando = true;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       limpiarFormulario();
    editando = false;
    productoSeleccionado = null;
}

private void limpiarFormulario() {
    txtNombreProducto.setText("");
    jFormattedTextField1.setText("");
    jCheckBox.setSelected(true);
    tblProductos.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActivarDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarDesactivarActionPerformed
       int fila = tblProductos.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "⚠️ Selecciona un producto.");
        return;
    }

    int id = (int) tblProductos.getValueAt(fila, 0);
    String nombre = (String) tblProductos.getValueAt(fila, 1);
    boolean estadoActual = "Activo".equals(tblProductos.getValueAt(fila, 3));

    String mensaje = estadoActual 
        ? "¿Deseas desactivar el producto '" + nombre + "'?" 
        : "¿Deseas activar el producto '" + nombre + "'?";

    int opcion = JOptionPane.showConfirmDialog(this, mensaje, "Confirmar", JOptionPane.YES_NO_OPTION);
    if (opcion == JOptionPane.YES_OPTION) {
        try {
            productoService.activarDesactivarProducto(id, !estadoActual);
            cargarProductosEnTabla(); // Refrescar
            JOptionPane.showMessageDialog(this, "✅ Estado actualizado.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "❌ Error al cambiar estado.");
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnActivarDesactivarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
     gui_principal gui_prin = new gui_principal(usuarioLogueado);
    gui_prin.setVisible(true);
    this.dispose(); // cierra la ventana actual
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarProductosEnTabla();
    JOptionPane.showMessageDialog(this, "🔄 Tabla actualizada.");
    }//GEN-LAST:event_btnRefrescarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarDesactivar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel panelCrud;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
