/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dominio.Usuario;

/**
 *
 * @author jh599
 */

public class gui_principal extends javax.swing.JFrame {
private Usuario usuarioLogueado;
    /**
     * Creates new form gui_principal
     */
  public gui_principal(Usuario usuario) {
    this.usuarioLogueado = usuario;
    initComponents(); 
     setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        btnGestionProducto = new javax.swing.JButton();
        btnRegistroVenta = new javax.swing.JButton();
        btnConsultaDia = new javax.swing.JButton();
        btnCalculadora = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnGestionProducto.setBackground(new java.awt.Color(153, 0, 51));
        btnGestionProducto.setText("Gestion producto");
        btnGestionProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProductoActionPerformed(evt);
            }
        });

        btnRegistroVenta.setBackground(new java.awt.Color(153, 0, 51));
        btnRegistroVenta.setText("Registro venta");
        btnRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroVentaActionPerformed(evt);
            }
        });

        btnConsultaDia.setBackground(new java.awt.Color(153, 0, 51));
        btnConsultaDia.setText("Consulta del día");
        btnConsultaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaDiaActionPerformed(evt);
            }
        });

        btnCalculadora.setBackground(new java.awt.Color(153, 0, 51));
        btnCalculadora.setText("Calculadora");
        btnCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(btnGestionProducto)
                .addGap(44, 44, 44)
                .addComponent(btnRegistroVenta)
                .addGap(54, 54, 54)
                .addComponent(btnConsultaDia)
                .addGap(56, 56, 56)
                .addComponent(btnCalculadora)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculadora)
                    .addComponent(btnConsultaDia)
                    .addComponent(btnRegistroVenta)
                    .addComponent(btnGestionProducto))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductoActionPerformed
      gui_gestion_productos gui_produc = new gui_gestion_productos (usuarioLogueado);
    gui_produc.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnGestionProductoActionPerformed

    private void btnRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroVentaActionPerformed
        gui_registro_venta gui_venta = new gui_registro_venta (usuarioLogueado);
    gui_venta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroVentaActionPerformed

    private void btnConsultaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaDiaActionPerformed
 gui_consulta_dia gui = new gui_consulta_dia(this, true, usuarioLogueado);
    gui.setVisible(true);   
    }//GEN-LAST:event_btnConsultaDiaActionPerformed
    
    private void btnCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculadoraActionPerformed
      gui_calcu gui_cal = new gui_calcu(this, true);  
    gui_cal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculadora;
    private javax.swing.JButton btnConsultaDia;
    private javax.swing.JButton btnGestionProducto;
    private javax.swing.JButton btnRegistroVenta;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
