/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author jh599
 */

import dominio.Producto;
import dominio.Usuario;
import dominio.DetalleVenta;
import servicio.ProductoServicio;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dominio.Venta;  
import servicio.VentaServicio;

public class gui_registro_venta extends javax.swing.JFrame {

    /**
     * Creates new form gui_registro_venta
     */
    
    private Usuario usuarioLogueado;
  private ProductoServicio productoService;
        private VentaServicio ventaService;
    
    public gui_registro_venta() {
    this.usuarioLogueado = usuario;
    this.productoService = new ProductoServicio();
    this.ventaService = new VentaServicio(); 
    
    initComponents();
    configurarTabla();
    setLocationRelativeTo(null);
    
    // Valor inicial del spinner
    jSpinnerCantidad.setValue(1);
    }
    
     private void configurarTabla() {
        // Configurar modelo de tabla vacío
        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }
     
private void actualizarTotales() {
        double subtotal = 0;
        
        // Calcular subtotal desde la tabla
        DefaultTableModel modelo = (DefaultTableModel) tblDetalles.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            double totalLinea = Double.parseDouble(modelo.getValueAt(i, 3).toString());
            subtotal += totalLinea;
        }
        
        // Calcular impuestos
        double iva = subtotal * 0.07;    // 7%
        double ivi = subtotal * 0.13;    // 13%
        double descuento = 0;
        
        if (jCheckBoxDescuento.isSelected()) {
            try {
                descuento = Double.parseDouble(lblDescuento.getText());
            } catch (NumberFormatException e) {
                descuento = 0;
            }
        }
        
        double total = subtotal + iva + ivi - descuento;
        
        // Actualizar etiquetas
        lblSubtotal.setText("Subtotal: $" + String.format("%.2f", subtotal));
        lblIva7.setText("IVA (7%): $" + String.format("%.2f", iva));
        lblIVI3.setText("IVI (13%): $" + String.format("%.2f", ivi));
        lblDescuento.setText("Descuento: $" + String.format("%.2f", descuento));
        lblTotal.setText("Total: $" + String.format("%.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscarNombre = new javax.swing.JLabel();
        txtBuscarNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jCheckBoxDescuento = new javax.swing.JCheckBox();
        lblSubtotal = new javax.swing.JLabel();
        lblIva7 = new javax.swing.JLabel();
        lblIVI3 = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnFinalizarVenta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNuevoItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscarNombre.setText("Buscar producto por nombre: ");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblDetalles);

        jCheckBoxDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDescuentoActionPerformed(evt);
            }
        });

        lblSubtotal.setText("Subtotal: $X.XX");

        lblIva7.setText("IVA (7%): $X.XX");

        lblIVI3.setText("IVI (13%): $X.XX");

        lblDescuento.setText("Descuento: $X.XX");

        lblTotal.setText("Total: $X.XX");

        btnFinalizarVenta.setText("Finalizar venta");
        btnFinalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVentaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevoItem.setText("Nuevo ítem");
        btnNuevoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIva7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIVI3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblBuscarNombre)
                        .addGap(43, 43, 43)
                        .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFinalizarVenta)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(29, 29, 29)
                                .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jCheckBoxDescuento))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnCancelar)
                                .addGap(80, 80, 80)
                                .addComponent(btnNuevoItem)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarNombre)
                    .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(btnAgregar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxDescuento)
                                    .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41)
                        .addComponent(lblSubtotal)
                        .addGap(29, 29, 29)
                        .addComponent(lblIva7)
                        .addGap(18, 18, 18)
                        .addComponent(lblIVI3)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescuento)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarVenta)
                    .addComponent(btnCancelar)
                    .addComponent(btnNuevoItem))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    String nombreBuscado = txtBuscarNombre.getText().trim();
        
        if (nombreBuscado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del producto.");
            return;
        }
        
        try {
            // Buscar producto por nombre
            Producto producto = productoService.buscarPorNombre(nombreBuscado);
            
            if (producto == null || !producto.isActivo()) {
                JOptionPane.showMessageDialog(this, "Producto no encontrado o inactivo.");
                return;
            }
            
            int cantidad = (Integer) jSpinnerCantidad.getValue();
            double totalLinea = cantidad * producto.getPrecioUnitario();
            
            // Agregar a la tabla
            DefaultTableModel modelo = (DefaultTableModel) tblDetalles.getModel();
            Object[] fila = {
                producto.getNombre(),
                cantidad,
                String.format("%.2f", producto.getPrecioUnitario()),
                String.format("%.2f", totalLinea)
            };
            modelo.addRow(fila);
            
            // Actualizar totales
            actualizarTotales();
            
            // Limpiar campos
            txtBuscarNombre.setText("");
            jSpinnerCantidad.setValue(1);
            txtBuscarNombre.requestFocus();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar producto: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jCheckBoxDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDescuentoActionPerformed
          if (jCheckBoxDescuento.isSelected()) {
            String descuentoStr = JOptionPane.showInputDialog(this, "Ingrese monto de descuento:");
            try {
                double descuento = Double.parseDouble(descuentoStr);
                if (descuento < 0) {
                    JOptionPane.showMessageDialog(this, "Descuento no puede ser negativo.");
                    jCheckBoxDescuento.setSelected(false);
                    return;
                }
                lblDescuento.setText(String.format("%.2f", descuento));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Monto inválido.");
                jCheckBoxDescuento.setSelected(false);
            }
        } else {
            lblDescuento.setText("0.00");
        }
        actualizarTotales();
    }//GEN-LAST:event_jCheckBoxDescuentoActionPerformed

    private void btnFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVentaActionPerformed
    if (tblDetalles.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Agregue al menos un producto.");
        return;
    }
    
    try {
        // Crear lista de detalles desde la tabla
        List<DetalleVenta> detalles = new ArrayList<>();
        DefaultTableModel modelo = (DefaultTableModel) tblDetalles.getModel();
        
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nombreProd = modelo.getValueAt(i, 0).toString();
            int cantidad = Integer.parseInt(modelo.getValueAt(i, 1).toString());
            double precioUnit = Double.parseDouble(modelo.getValueAt(i, 2).toString());
            double totalLinea = Double.parseDouble(modelo.getValueAt(i, 3).toString());
            
            // Buscar producto por nombre
            Producto producto = productoService.buscarPorNombre(nombreProd);
            
            if (producto != null) {
                DetalleVenta detalle = new DetalleVenta(
                    0, null, producto, cantidad, precioUnit, totalLinea
                );
                detalles.add(detalle);
            }
        }
        
        double descuento = 0;
        if (jCheckBoxDescuento.isSelected()) {
            try {
                descuento = Double.parseDouble(lblDescuento.getText());
            } catch (NumberFormatException e) {
                descuento = 0;
            }
        }
        
        // Registrar venta - CORREGIDO
        Venta ventaRegistrada = ventaService.registrarVenta(usuarioLogueado, detalles, descuento);
        
        JOptionPane.showMessageDialog(this, "✅ Venta #" + ventaRegistrada.getId() + " registrada con éxito.");
        
        // Limpiar todo
        modelo.setRowCount(0);
        lblDescuento.setText("0.00");
        jCheckBoxDescuento.setSelected(false);
        actualizarTotales();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar venta: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnFinalizarVentaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      DefaultTableModel modelo = (DefaultTableModel) tblDetalles.getModel();
        modelo.setRowCount(0);
        lblDescuento.setText("0.00");
        jCheckBoxDescuento.setSelected(false);
        actualizarTotales();
        JOptionPane.showMessageDialog(this, "Venta cancelada.");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoItemActionPerformed
          txtBuscarNombre.setText("");
        jSpinnerCantidad.setValue(1);
        txtBuscarNombre.requestFocus();
    }//GEN-LAST:event_btnNuevoItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarVenta;
    private javax.swing.JButton btnNuevoItem;
    private javax.swing.JCheckBox jCheckBoxDescuento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JLabel lblBuscarNombre;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblIVI3;
    private javax.swing.JLabel lblIva7;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblDetalles;
    private javax.swing.JTextField txtBuscarNombre;
    // End of variables declaration//GEN-END:variables
}
